[build]
  # Directory that contains the deploy-ready HTML files
  publish = "dist"
  # Build optimized assets with Vite before deploy
  command = "npm run build"

[[redirects]]
  # Handle any routing needs
  from = "/*"
  to = "/index.html"
  status = 200